### PR TITLE
Blogger App Functional Changes and Error Fixes

### PR DESCRIPTION
**Pull request by AKindley**
Made a number of functional and QoL changes to the blogger app based on this [list of priorities.](https://docs.google.com/presentation/d/1bnftz08_1eOqHyVAYwNEYXEOr4a3rUc5CQNmchWkwf8/edit?ts=5b948e30#slide=id.p)

Some extra changes outside the given priorities were made to address redirects and page refreshing issues.

### CODE REVIEW

**Comment by AKindley** [comment]
Secret.json contains the google api credentials as per secret.json.example. Without changes to the credentials this pull won't deploy correctly.

**Comment by noway** [comment]
do you still wanna merge this?

**Comment by noway** [comment]
Also i don't have much time to maintain this repo unfortunately as because I have other life commitments atm. I can gladly assist in transferring any credentials/access needed to run this app.

**Comment by handankel** [comment]
Probably best you don't

We have a new deployment from our fork.  And have capacity to maintain.

We plan to transition to this deployment this year.

In the mean time please leave your deployment  as is.  I or someone from
the trust will let you now when we have switched to the new deployment and
you can decomison yours.

Thanks for all the work you have done on this

**Comment by noway** [comment]
Sweet, I've added a link to your repo in the README. I would have gladly continued work on this, but sadly i have other life commitments. Sorry on being unresponsive on my part.

Cheers

**Pull request closed without merging**
